Feature/events
m4rrc0/astro-wplay pull request #4
Opened 2024-08-05 21:58 UTC by LirycMoaners

2024-08-16 11:15 UTC, m4rrc0 requested changes
Wow, what a job !
We should discuss to see who handles what.
There are a few small tweaks on the design side. I didn't comment on everything. Maybe I should look at this first.
Also, I need to merge your work and mine at some point because there is some overlap.

2024-08-16 11:15 UTC, m4rrc0 commented on public/assets/js/events-filter.js
> +  navigator.geolocation.getCurrentPosition((pos) => visitorPosition = pos);
We should only do this when the user clicks "Ma position".
Ideally, clicking "Ma position" should open a dialog explaining that we need their consent to grab their precise location and that the info is only used on the frontend and never stored on our end. Then clicking "Ok" would trigger the default browser prompt while "Refuser" would dismiss it.
And I guess we should save this choice in local storage

Optionally, if the user has previously agreed to share their location, we might want to select "Ma position" automatically?

2024-08-16 11:15 UTC, m4rrc0 commented on public/assets/js/organizations-filter.js
It would be nice to have a "reset" option for each filter individually. It is quite tedious to uncheck many categories and frustrating to have to reset the whole filtering if we want to reset just one aspect.

I am wondering if we shouldn't be using [framework components](https://docs.astro.build/en/guides/framework-components/) for this dynamic part. Any lightweight option would suit me just fine. Svelte is already installed on the project.

To be honest, I feel like it is a lot of code we will not want to touch in 6 months... I am sorry, because I know you spent a lot of time on this... but let's at least open the discussion about a framework integration, maybe for a future refactoring.

2024-08-16 11:15 UTC, m4rrc0 commented on public/assets/js/organizations-filter.js
> +    serviceBtn.innerText = 'Types';
This should reset to "Services"

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/BasicPage.astro
> +          <li class="dropdown">
The dropdowns need a visual cue. The classic triangle might do the trick.
Also they need to close when clicking anywhere outside.
We should probably use the [popover element](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover) with targets and auto close ([MDN demo](https://mdn.github.io/dom-examples/popover-api/multiple-auto/)).
We might want to polyfill it because support is only at 86% right now.

For accessibility's sake, we should probably have proper pages for "Ressources" and "A propos" in case a visitor has no JS. These pages could be super simple with a title and 2 links and be removed from the sitemap.
If JS kicks in, the `a` tag gets replaced by a button that triggers the popover behavior.

... More discussion to be had here...

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/SkeletonPage.astro
> +    <link href="/pagefind/pagefind-ui.css" rel="stylesheet" />
I think you intended to put a `pagefind` folder in the `public` directory but it is not there.

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/BasicPage.astro
> +  <dialog id="searchContainer" class="width-max" style="height: 100%; background-color: transparent;">
We are missing the pagefind stylesheet.

Moreover, this shouldn't be completely broken without the stylesheet. The basic dialog functionality should still work.

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/BasicPage.astro
> +    flex-basis: 0;
Menu items can overlap with this. There must be a better solution. What are you trying to achieve?

2024-08-16 11:15 UTC, m4rrc0 commented on src/services/directus.js
> +  const a = (location?.[0]?.zip && location?.[0]) || (location?.zip && location) || (address?.[0]?.zip && address?.[0]) || (address?.zip && address)
location is not intended to ever be an array. Any good reason to keep this "just in case"?

2024-08-16 11:15 UTC, m4rrc0 commented on src/services/directus.js
> +  const address = transformAddress(o.address, o.location ? {
I would add a comment to refactor this later.
It feels weird to keep the old syntax while we will only use the `location` moving forward.
I get why you did it but I want to remember to come back to this later.

2024-08-16 11:15 UTC, m4rrc0 commented on src/services/directus.js
> +  const address = transformAddress(e.address, e.location ? {
idem than in transformOrganization

2024-08-16 11:15 UTC, m4rrc0 commented on src/styles/layout.css
> +  white-space: nowrap;
Where on the website is this needed?

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/EventsPage.astro
> +              <div id="eventType" class="dropdown-content align-items-start">
This shows partly off-screen on mobile.
It makes sense to use a `<popover>` here too (see comments for the main nav).

Accessibility seems good right now...
Buttons should be disabled when no JS.

2024-08-16 11:15 UTC, m4rrc0 commented on src/styles/layout.css
> +.text-overflow-ellipsis {
I would prefer this to be in `utility.css` or `main.css`

As context, `layout.css` contains generic pieces of page layout. It is heavily inspired by [Every Layout](https://every-layout.dev/). It will be updated someday so it is easier to keep it clean of other non related classes declarations.

2024-08-16 11:15 UTC, m4rrc0 commented on src/styles/utility.css
> +.dropdown-content {
Can we avoid setting fixed values in px?

2024-08-16 11:15 UTC, m4rrc0 commented on src/styles/vars.css
> +body {
to be reviewed when pagefind results show up properly...

2024-08-16 11:15 UTC, m4rrc0 commented on src/styles/utility.css
> +.show {
I would either change the logic and have a `.hidden` class or call this class `.block` just to avoid confusion (e.g. using the class `.show` on a flex container)

2024-08-16 11:15 UTC, m4rrc0 commented on src/styles/utility.css
> +.pagefind-ui__drawer {
to be reviewed when pagefind results show up properly...

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/BasicPage.astro
> +          <Icon
Should be (and look) disabled when no JS

2024-08-16 11:15 UTC, m4rrc0 commented on public/assets/js/events-filter.js
Please see general comments on `organizations-filter.js`

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/OrganizationsPage.astro
> +                          const currentPalette = `color-palette-${type.code_name}`
This can be defined from the CMS now. Dictionary items have a field `colorPalette`. So this should be:
```
const currentPalette = `color-palette-${type.colorPalette}`
```

2024-08-16 11:15 UTC, m4rrc0 commented on src/services/directus.js
> +				"organization_types.type.code_name",
We should also fetch:
```
"organization_types.type.colorPalette"
```
⚠ This should be applied to anywhere we call a dictionary item.

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/OrganizationsPage.astro
> +                          style="width: 120px; max-width: 100%; height: auto; max-height: 120px;"
This needs an `object-fit:contain`

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/OrganizationsPage.astro
> +      <div id="events-list-container" class="box no-border stack gap-down-h1">
change the id

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/OrganizationsPage.astro
> +        <IO h2 $skip={!organizations?.[0]} class="center text">
should be an h1

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/OrganizationsPage.astro
> +                  <li
needs a `max-width`. Something like 15rem...

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/OrganizationsPage.astro
I put a few comments in here but I'll probably dive in the design and make the changes myself.

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/EventsPage.astro
Let's keep in touch to see who finalizes the design.

2024-08-16 11:15 UTC, m4rrc0 commented on src/layouts/EventPage.astro
Let's keep in touch to see who finalizes the design.

2024-08-16 11:15 UTC, m4rrc0 commented on src/services/directus.js
> +				"code_name",
fetch `colorPalette` as well

2024-08-18 08:29 UTC, LirycMoaners commented on src/layouts/SkeletonPage.astro
> +    <link href="/pagefind/pagefind-ui.css" rel="stylesheet" />
You just need to run the pagefind script to have it for dev purposes

2024-08-18 08:33 UTC, LirycMoaners commented on src/layouts/BasicPage.astro
> +  <dialog id="searchContainer" class="width-max" style="height: 100%; background-color: transparent;">
You just need to run the pagefind script to have it for dev purposes

2024-08-18 09:06 UTC, LirycMoaners commented on src/services/directus.js
> +  const address = transformAddress(o.address, o.location ? {
Refactored

2024-08-18 09:06 UTC, LirycMoaners commented on src/services/directus.js
> +  const address = transformAddress(e.address, e.location ? {
Refactored

2024-08-18 09:12 UTC, LirycMoaners commented on src/styles/vars.css
> +body {
You just need to run the pagefind script to have it for dev purposes

2024-08-18 09:12 UTC, LirycMoaners commented on src/styles/utility.css
> +.pagefind-ui__drawer {
You just need to run the pagefind script to have it for dev purposes

2024-08-18 10:47 UTC, m4rrc0 commented on src/layouts/OrganizationsPage.astro
> +                          const currentPalette = `color-palette-${type.code_name}`
Or, just to be safe...

```
const currentPalette = `color-palette-${type.colorPalette || type.code_name}`
```

2024-08-18 10:49 UTC, m4rrc0 commented on src/styles/vars.css
> +body {
Oh, right !
I didn't expect the library to generate the CSS file on the fly as well.
Thanks.

2024-08-18 14:17 UTC, LirycMoaners commented on src/layouts/EventsPage.astro
For the design, everything depends on the scope and the release date. If you (Jenny, Roxane and you) want to release before the BGF, I will not have the time to finalize the design before that event. But if we release after, I can work on it. Also, I don't know if that's really a problem if we have an intermediate version for the BGF without the final design.

2024-08-19 09:16 UTC, m4rrc0 commented on src/layouts/EventsPage.astro
Absolutely. An intermediate version for the BGF is the goal. We just need to set a limit on the scope like you said.
Let's keep this part for the end as it is functional right now.

2024-08-19 12:02 UTC, LirycMoaners commented on src/layouts/BasicPage.astro
> +          <li class="dropdown">
Just to mention that regarding market share for browsers usage, popover will not work for 9% of Belgium devices.

2024-08-19 12:06 UTC, LirycMoaners commented on src/layouts/BasicPage.astro
> +          <Icon
Do we really want to spend time on this as browsers market share shows around 2% of Belgium devices with no JS enabled

2024-08-19 12:14 UTC, LirycMoaners commented on src/layouts/OrganizationsPage.astro
> +                          style="width: 120px; max-width: 100%; height: auto; max-height: 120px;"
Not the case in AreaPage

2024-08-19 12:16 UTC, LirycMoaners commented on src/layouts/OrganizationsPage.astro
> +                  <li
Not the case in AreaPage

2024-08-19 18:02 UTC, LirycMoaners commented on src/layouts/EventsPage.astro
> +              <div id="eventType" class="dropdown-content align-items-start">
Popover is now used here

2024-08-19 18:03 UTC, LirycMoaners commented on src/layouts/BasicPage.astro
> +          <li class="dropdown">
Popover is now used here. And I added the triangle.

2024-08-19 20:41 UTC, LirycMoaners commented on public/assets/js/events-filter.js
> +  navigator.geolocation.getCurrentPosition((pos) => visitorPosition = pos);
Now geolocation is asked only when user click "Ma position".

2024-08-20 09:58 UTC, m4rrc0 commented on src/layouts/OrganizationsPage.astro
> +                  <li
The list of Orgs on AreaPage can not be filtered so we never end up with only one element in the list. Having only one Org in the list is ugly when it spans the whole width of the page.
I will set it globally in `main.css`.

2024-08-20 14:13 UTC, m4rrc0 commented on src/layouts/BasicPage.astro
> +          <li class="dropdown">
Thanks. I don't see the triangles but let's close this for now as we will certainly change some things in the nav sooner than later.

2024-08-20 14:19 UTC, merged